import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "sonner";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

const inter = Figtree({subsets : ["latin"] });

export const metadata: Metadata = {
    title: "Safari",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth();

    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session} >
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        disableTransitionOnChange
                    >
                        <QueryProvider>
                            <Toaster position="bottom-right" />
                            {children}
                        </QueryProvider>
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
